version = 5.8.0
archive_dir = /config/etc/letsencrypt/archive/hyvka.kitek-pg.ru
cert = /config/etc/letsencrypt/live/hyvka.kitek-pg.ru/cert.pem
privkey = /config/etc/letsencrypt/live/hyvka.kitek-pg.ru/privkey.pem
chain = /config/etc/letsencrypt/live/hyvka.kitek-pg.ru/chain.pem
fullchain = /config/etc/letsencrypt/live/hyvka.kitek-pg.ru/fullchain.pem
[renewalparams]
account = 0b1cc7ce183ddac61c3b7301909b22c3
pref_challs = http-01,
config_dir = /config/etc/letsencrypt
work_dir = /tmp/letsencrypt
logs_dir = /config/log/letsencrypt
server = https://acme-v02.api.letsencrypt.org/directory
authenticator = standalone
key_type = ecdsa
